version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      JWT_SECRET: supersecret
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm start

volumes:
  postgres-data: